name: Linux x86-64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # download jdk
      - run: wget -O $RUNNER_TEMP/java_package.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.6-linux-x64-b825.69.tar.gz

      # install jdk
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21.0.6'
          architecture: x64

      # dist
      - run: |
          ./gradlew dist --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-linux-x86-64
          path: build/distributions/*.tar.gz
