name: macOS

on: [ push, pull_request ]

env:
  TERMORA_MAC_SIGN: "${{ github.repository == 'TermoraDev/termora' }}"
  TERMORA_MAC_SIGN_USER_NAME: ${{ secrets.TERMORA_MAC_SIGN_USER_NAME }}
  # 只有发布版本时才需要公证
  TERMORA_MAC_NOTARY: "${{ startsWith(github.event.head_commit.message, 'release: ') && github.repository == 'TermoraDev/termora' }}"
  TERMORA_MAC_NOTARY_KEYCHAIN_PROFILE: ${{ secrets.TERMORA_MAC_NOTARY_KEYCHAIN_PROFILE }}
  JBR_MAJOR: 21.0.7
  JBR_PATCH: b1038.58

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-15, macos-13 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install the Apple certificate
        if: "env.TERMORA_MAC_SIGN && env.BUILD_CERTIFICATE_BASE64 != ''"
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Setup the Notary information
        if: "env.TERMORA_MAC_NOTARY && env.APPLE_ID != ''"
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          STORE_CREDENTIALS: ${{ secrets.TERMORA_MAC_NOTARY_KEYCHAIN_PROFILE }}
        run: |
          xcrun notarytool store-credentials "$STORE_CREDENTIALS" --apple-id "$APPLE_ID" --team-id "$TEAM_ID" --password "$APPLE_PASSWORD"

      - name: Download Java
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            ARCH="aarch64"
          else
            ARCH="x64"
          fi
          wget -q -O $RUNNER_TEMP/java_package.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-${{ env.JBR_MAJOR }}-osx-$ARCH-${{ env.JBR_PATCH }}.tar.gz

      # install jdk
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21.0.7'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-

      - name: Compile
        shell: bash
        run: ./gradlew :check-license && ./gradlew classes -x test

      - name: JLink
        shell: bash
        run: ./gradlew :jar :copy-dependencies :plugins:migration:build :jlink

      - name: Package
        shell: bash
        run: ./gradlew :jpackage && ./gradlew :dist

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-osx-zip-${{ runner.arch }}
          path: |
            build/distributions/*.zip

      - name: Upload dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-osx-dmg-${{ runner.arch }}
          path: |
            build/distributions/*.dmg
