name: Windows x86-64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - run: curl --output ${{ runner.temp }}/java_package.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.5-windows-x64-b509.30.tar.gz

      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21.0.509+30'

      # dist
      - run: |
          .\gradlew.bat dist --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-windows-x86-64
          path: build/distributions/*.tar.gz